baseURL = "https://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"

# Metadata for SEO and social sharing
description = "This is a test."
author = "Darko Anautov"

# Enable RSS feed (optional)
enableRSS = true

# Enable Sitemap (optional)
enableSitemap = true

[menu]
  [[menu.main]]
    name = "Products"
    url = "#products"
    weight = 1
  [[menu.main]]
    name = "Solutions"
    url = "#solutions"
    weight = 2
  [[menu.main]]
    name = "Resources"
    url = "#resources"
    weight = 3
  [[menu.main]]
    name = "Company"
    url = "#company"
    weight = 4
  [[menu.main]]
    name = "Pricing"
    url = "#pricing"
    weight = 5
    
[params]
  productName = "Optmyzr"
  privacyPolicyURL = "/privacy-policy"
  termsOfUseURL = "/terms-of-use"
  features = ["One-Click Optimizations", "Data Insights", "Enhanced Scripts", "Rule Engine", "Optmyzr Express", "Blue Prints"]
  solutions = ["Search Ads", "Shopping Ads", "Google Ads", "Microsoft Ads", "Amazon Ads", "Agencies", "Custom"]
  company = ["About", "Blog", "PPC Town Hall", "Case Studies", "Events", "Help Center", "Affiliate Program", "Book"]

[params.contact]
write_to_us_url = "/contact"
demo_url = "/demo"

[[params.social]]
name = "Twitter"
icon = "images/twitter.png"

[[params.social]]
name = "Instagram"
icon = "images/instagram.png"

[trusted_heading]
  other = "Paid media and digital marketing teams all over the world use Optmyzr"

[trusted_subheading]
  other = "See how PPC teams the world over improve performance, increase efficiency, and scale their businesses with Optmyzr."

[params.case_study]
heading = "Matthieu Tran-Van sees 10x productivity boost & 28% Revenue surge through Optmyzr"
subheading = "Google Ads Expert saves 20 account management hours weekly, cuts CPCs, and boosts revenue through automated optimizations"
read_story_text = "Read Full Story"
book_demo_text = "Book Demo"

[params.caseStudies]
title = "See how PPC teams around the world improve performance, increase efficiency, and scale their businesses with Optmyzr."
load_more_text = "Load More Stories"

[case_studies]
brand = "BRAND"
title = "BBQGuys Manages Nearly 30,000 SKUs in 50% Less Time with Optmyzr"
description = "Louisiana-based online retailer saves 4-6 hours weekly and gains over $450k in revenue since 2021"
image = "images/placeholder_1.png"
button_text = "Read Full Story"




